server:
  port: 9700
spring:
  application:
    name: written-exam
  security:
    user:
      name: test
      password: 123456
whiteApi: /login

jwt:
  secret: my_secret
  expirationTime: 36000
  issuer: hello
  header: Authorization
  tokenHead: Bearer

